name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dorbella:$(date +%s)
 
    - name: Connect Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TS_OAUTH_SECRET }}
